name: Deploy App

on:
  workflow_call:
    inputs:
      app:
        description: Name of the app to deploy, like esapi or queue
        required: true
        type: string
      image_repo:
        description: Image repo, like ghcr.io/simpleanalytics/elasticsearch
        required: true
        type: string
      image_tag:
        description: Tag to deploy, defaults to github.sha
        required: false
        default: ""
        type: string
      hosts:
        description: Space-separated list of hosts to deploy to
        required: false
        default: "esapp01 esapp02 esapp03"
        type: string

jobs:
  deploy:
    name: Deploy via webhook
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: deploy-${{ inputs.env }}
    steps:
      - name: Disable deploys for maintenance
        run: |
          echo "Deployments are disabled for maintenance"
          exit 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image as production
        if: ${{ inputs.image_tag != 'production' }}
        run: |
          docker pull ${{ inputs.image_repo }}:${{ inputs.image_tag || github.sha }}
          docker tag ${{ inputs.image_repo }}:${{ inputs.image_tag || github.sha }} ${{ inputs.image_repo }}:production
          docker push ${{ inputs.image_repo }}:production

      - name: Trigger deployment webhook with output
        run: |
          set -uo pipefail # no "e" because we want to retrieve the curl output

          read -a hosts <<< "${{ inputs.hosts }}"
          fail_flag=0 # Flag to track if any command fails

          for host in "${hosts[@]}"; do
            curl -sS --fail-with-body --user "token:${{ secrets.DEPLOY_TOKEN }}" \
              --write-out "%{http_code}" --output response_$host.tmp \
              "https://webhook.$host.simpleanalytics.com/deploy?app=${{ inputs.app }}" > status_$host.txt 2>&1 &
          done

          for pid in $(jobs -p); do
            if ! wait "$pid"; then
              fail_flag=1 # Set fail flag if a process fails
            fi
          done

          # Read status codes and responses after all jobs have completed
          for host in "${hosts[@]}"; do
            echo "::group::Webhook output for $host"
            echo "Host $host:"
            echo "HTTP Status Code: $(cat status_$host.txt)"
            echo "Response Body:"
            cat response_$host.tmp || echo "No response body found"
            echo "" # for better readability
            echo "::endgroup::"
          done

          if [ "$fail_flag" -ne 0 ]; then
            exit 1 # Exit with status 1 if any command failed
          fi
